
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 44;
  public static final int MULT = 22;
  public static final int CORCH_IZQ = 39;
  public static final int IMPRIMIR = 13;
  public static final int CASE = 8;
  public static final int DIFERENTE = 27;
  public static final int RESTA = 21;
  public static final int DOS_PUNTOS = 43;
  public static final int LPAREN = 35;
  public static final int T_INT = 14;
  public static final int FOR = 6;
  public static final int RPAREN = 36;
  public static final int LLAVE_IZQ = 37;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int DIV = 23;
  public static final int SUMA = 20;
  public static final int ASSIGN = 25;
  public static final int MAIN = 2;
  public static final int IF = 3;
  public static final int T_CHAR = 15;
  public static final int ID = 45;
  public static final int PUNTO_COMA = 41;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int TRUE = 18;
  public static final int error = 1;
  public static final int COMA = 42;
  public static final int CORCH_DER = 40;
  public static final int MENOR = 28;
  public static final int LIT_CHAR = 46;
  public static final int MOD = 24;
  public static final int BREAK = 10;
  public static final int SWITCH = 7;
  public static final int MAYOR = 29;
  public static final int ELSE = 4;
  public static final int LLAVE_DER = 38;
  public static final int T_BOOL = 16;
  public static final int WHILE = 5;
  public static final int IGUAL_QUE = 26;
  public static final int DEFAULT = 9;
  public static final int MAYOR_IGUAL = 31;
  public static final int LEER = 12;
  public static final int MENOR_IGUAL = 30;
  public static final int FALSE = 19;
  public static final int T_VOID = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "LEER",
  "IMPRIMIR",
  "T_INT",
  "T_CHAR",
  "T_BOOL",
  "T_VOID",
  "TRUE",
  "FALSE",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "MOD",
  "ASSIGN",
  "IGUAL_QUE",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "CORCH_IZQ",
  "CORCH_DER",
  "PUNTO_COMA",
  "COMA",
  "DOS_PUNTOS",
  "NUMERO",
  "ID",
  "LIT_CHAR"
  };
}

